// Generated by LiveScript 1.2.0
var gulp, gulpUtil, gulpJade, gulpLivescript, gulpConcat, gulpUglify, gulpLivereload, tinyLr, express, path, app, server, EXPRESSPORT, LIVERELOADPORT;
gulp = require('gulp');
gulpUtil = require('gulp-util');
gulpJade = require('gulp-jade');
gulpLivescript = require('gulp-livescript');
gulpConcat = require('gulp-concat');
gulpUglify = require('gulp-uglify');
gulpLivereload = require('gulp-livereload');
tinyLr = require('tiny-lr');
express = require('express');
path = require('path');
app = express();
server = tinyLr();
EXPRESSPORT = 3000;
LIVERELOADPORT = 35729;
gulp.task('jade', function(){
  return gulp.src('src/*.jade').pipe(gulpJade({
    pretty: true
  })).pipe(gulp.dest('.')).pipe(gulpLivereload(server));
});
gulp.task('ls', function(){
  return gulp.src('src/*.ls').pipe(gulpLivescript()).pipe(gulp.dest('.'));
});
gulp.task('build', ['ls'], function(){
  return gulp.src(['lib/laweasyread.debug.js', 'laweasyread.js']).pipe(gulpConcat('angular-laweasyread.js')).pipe(gulpUglify()).pipe(gulp.dest('.'));
});
gulp.task('express', function(){
  app.use(require('connect-livereload')());
  app.use(express['static'](path.resolve('.')));
  app.listen(EXPRESSPORT);
  return gulpUtil.log('Listening on port: ' + EXPRESSPORT);
});
gulp.task('watch', ['jade', 'build'], function(){
  return server.listen(LIVERELOADPORT, function(it){
    if (it) {
      return gulpUtil.log(it);
    }
    gulp.watch('src/*.jade', ['jade']);
    return gulp.watch('src/*.ls', ['build']);
  });
});
gulp.task('default', ['express', 'watch']);